#!/usr/bin/env python3
"""ROS executable that also supports direct execution from a source workspace."""

import os
import sys


# roslaunch can resolve the source script when the workspace has not been
# sourced yet. Keep that deployment mode functional without affecting the
# relay script generated by catkin in devel/lib.
_SOURCE_PACKAGE_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), os.pardir, "src")
)
if os.path.isdir(os.path.join(_SOURCE_PACKAGE_ROOT, "ros_udp_telemetry")):
    sys.path.insert(0, _SOURCE_PACKAGE_ROOT)

from ros_udp_telemetry.node import run


if __name__ == "__main__":
    run()
